import { Box } from "@mui/material";
import AppHeader from "components/AppHeader";
import AppNavigationDrawer from "components/Common/Drawer/AppNavigationDrawer";
import MiniDrawer from "components/Common/Drawer/MiniDrawer";
import PublishPageDrawer from "components/Common/Drawer/PublishPageDrawer";
import API_URL from "constants/API_URL";
import {
  DEMO_DEVELOPMENT_URL,
  DEMO_PRODUCTION_URL,
  DEMO_USER_EMAIL,
} from "constants/APP_CONSTANTS";
import drawerNavLinks from "constants/navigation/drawerNav";
import publishPageNavLinks from "constants/navigation/publishPageNavLinks";
import API_RESPONSE_STATUS from "constants/status/apiResponseStatus";
import Head from "next/head";
import { useRouter } from "next/router";
import { enqueueSnackbar } from "notistack";
import React, { useEffect } from "react";
import { useCookies } from "react-cookie";
import { useDispatch, useSelector } from "react-redux";
import { signOutUser } from "redux/user/userSlice";
import appFetch from "utils/appFetch";

const mapState = ({ user }) => ({
  currentUser: user.currentUser,
});
export default function PublishPageLayout({
  pageTitle,
  children,
  drawerTitle,
  links,
}) {
  const { currentUser } = useSelector(mapState);
  const router = useRouter();
  const dispatch = useDispatch();
  const [cookies, setCookie, removeCookie] = useCookies(["access_token"]);

  const handleValidateLoginToken = () => {
    const URL = API_URL.VALIDATE_LOGIN_TOKEN;
    const data = {
      user_id: currentUser.merchant_id,
      login_token: currentUser.login_token,
    };
    if (
      currentUser.merchant_email === DEMO_USER_EMAIL &&
      (window.location.host === DEMO_PRODUCTION_URL ||
        window.location.host === DEMO_DEVELOPMENT_URL)
    ) {
      return;
    }

    appFetch(URL, data)
      .then((json) => {
        if (json.status === API_RESPONSE_STATUS.SUCCESS) {
          console.log("token validated");
        }
        if (json.status === API_RESPONSE_STATUS.FAILURE) {
          dispatch(signOutUser());
          removeCookie("access_token", {
            path: "/",
            domain:
              process.env.NODE_ENV === "production" ? ".bluecom.ai" : undefined,
          });

          enqueueSnackbar("Session expired. Please login again.", {
            variant: "error",
          });
          router.push("/auth/login");
          setTimeout(() => {
            router.reload();
          }, 1200);
        }
      })
      .catch((error) => {
        console.error(error);
      });
  };
  useEffect(() => {
    if (currentUser) {
      handleValidateLoginToken();
    }
  }, [currentUser]);

  useEffect(() => {
    if (!currentUser) {
      router.push("/auth/login");
    }
  }, [currentUser]);

  return (
    <Box>
      <Head>
        <title>{pageTitle || "Ecommerce Dashboard App"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AppHeader /> */}

      <PublishPageDrawer links={links} pageTitle={drawerTitle}>
        {children}
      </PublishPageDrawer>
    </Box>
  );
}
