import { Box } from "@mui/material";
import AppHeader from "components/AppHeader";
import OnboardingHeader from "components/AppHeader/OnboardingHeader";
import AppNavigationDrawer from "components/Common/Drawer/AppNavigationDrawer";
import MiniDrawer from "components/Common/Drawer/MiniDrawer";
import PublishPageDrawer from "components/Common/Drawer/PublishPageDrawer";
import StepperDrawer from "components/Common/Drawer/StepperDrawer";
import API_URL from "constants/API_URL";
import {
  DEMO_DEVELOPMENT_URL,
  DEMO_PRODUCTION_URL,
  DEMO_USER_EMAIL,
} from "constants/APP_CONSTANTS";
import drawerNavLinks from "constants/navigation/drawerNav";
import publishPageNavLinks from "constants/navigation/publishPageNavLinks";
import API_RESPONSE_STATUS from "constants/status/apiResponseStatus";
import Head from "next/head";
import { useRouter } from "next/router";
import { enqueueSnackbar } from "notistack";
import React, { useEffect } from "react";
import { useCookies } from "react-cookie";
import { useDispatch, useSelector } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { persistor } from "redux/configureStore";
import { signOutUser } from "redux/user/userSlice";
import appFetch from "utils/appFetch";

const mapState = ({ user }) => ({
  currentUser: user.currentUser,
});
export default function StorePageLayout({
  pageTitle,
  children,
  drawerTitle,
  links,
  RouterPushUrl,
  drawerDescription,
  disableAllStepsOnSuccess,
}) {
  const { currentUser } = useSelector(mapState);
  const router = useRouter();
  const dispatch = useDispatch();
  const [cookies, setCookie, removeCookie] = useCookies(["access_token"]);

  const handleValidateLoginToken = () => {
    const URL = API_URL.VALIDATE_LOGIN_TOKEN;
    const data = {
      user_id: currentUser.merchant_id,
      login_token: currentUser.login_token,
    };

    if (
      currentUser.merchant_email === DEMO_USER_EMAIL &&
      (window.location.host === DEMO_PRODUCTION_URL ||
        window.location.host === DEMO_DEVELOPMENT_URL)
    ) {
      return;
    }

    appFetch(URL, data)
      .then((json) => {
        if (json.status === API_RESPONSE_STATUS.SUCCESS) {
          console.log("token validated");
        }
        if (json.status === API_RESPONSE_STATUS.FAILURE) {
          dispatch(signOutUser());
          removeCookie("access_token", {
            path: "/",
            domain:
              process.env.NODE_ENV === "production" ? ".bluecom.ai" : undefined,
          });

          enqueueSnackbar("Session expired. Please login again.", {
            variant: "error",
          });
          setTimeout(() => {
            router.reload();
          }, 1200);

          router.push("/auth/login");
        }
      })
      .catch((error) => {
        console.error(error);
      });
  };
  useEffect(() => {
    if (currentUser) {
      handleValidateLoginToken();
    }
  }, [currentUser]);

  useEffect(() => {
    if (!currentUser) {
      router.push("/auth/login");
    }
  }, [currentUser]);

  return (
    <Box>
      <PersistGate persistor={persistor}>
        <Head>
          <title>{pageTitle || "Bluecom Dashboard - Store Onboarding"}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <AppHeader /> */}
        <OnboardingHeader RouterPushUrl={RouterPushUrl} />

        <StepperDrawer
          links={links}
          // pageTitle={drawerTitle || "Add a store"}
          // drawerTitle={drawerTitle || "Add a store"}
          pageTitle={drawerTitle || "Connect your store"}
          drawerTitle={drawerTitle || "Connect your store"}
          drawerDescription={
            drawerDescription || "Follow these steps to connect in a few clicks"
          }
          keyForReduxData="store"
          disableAllStepsOnSuccess
          drawerPaperWidth={`320px`}
        >
          {children}
        </StepperDrawer>
      </PersistGate>
    </Box>
  );
}
